name: circular_reveal_animation
description:
  Circular Reveal Animation as Flutter widget!
  Inspired by Android's ViewAnimationUtils.createCircularReveal(...).
version: 1.0.3
author: Alexander Zhdanov <qwert2603@mail.ru>
homepage: https://github.com/qwert2603/circular_reveal_animation

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
