name: circular_reveal_animation
description: Circular Reveal Animation
version: 0.0.1
author: qwert2603
homepage: https://github.com/qwert2603/circular_reveal_animation

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
